- id: '1764084273780'
  name: Zuhause
  entities: {}
  metadata: {}
  icon: mdi:home-account
- id: '1764084306845'
  name: Abwesend
  entities: {}
  icon: mdi:home-export-outline
  metadata: {}
- id: '1764084355901'
  name: Urlaub
  entities: {}
  icon: mdi:beach
  metadata: {}
- id: '1764084388381'
  name: Nacht
  entities: {}
  icon: mdi:weather-night
  metadata: {}
- id: '1764084409344'
  name: Morgen
  entities: {}
  icon: mdi:weather-sunset-up
  metadata: {}
- id: '1764084432779'
  name: Home-Office
  entities: {}
  icon: mdi:chair-rolling
  metadata: {}
- id: '1764084463454'
  name: Filmabend
  entities: {}
  icon: mdi:movie-open
  metadata: {}
