version: "3.7"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: pihole.bause.local
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: always

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # DHCP Server Usage
      - "${HTTPPORT}:80/tcp"
      #- "${HTTPSPORT}:443/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      #DNS1: ${DNSSERVER1}
      #DNS2: ${DNSSERVER2}
      #FTLCONF_LOCAL_IPV4: 192.168.41.55
      #PROXY_LOCATION: pihole
      #VIRTUAL_HOST: pihole.yourDomain.lan
      #VIRTUAL_PORT: 80
      #CONDITIONAL_FORWARDING: ${CONDITIONAL_FORWARDING}
      #CONDITIONAL_FORWARDING_IP: ${CONDITIONAL_FORWARDING_IP}
      #CONDITIONAL_FORWARDING_DOMAIN: ${CONDITIONAL_FORWARDING_DOMAIN}
      #CONDITIONAL_FORWARDING_REVERSE: ${CONDITIONAL_FORWARDING_REVERSE}
    # Volumes store your data between container upgrades
    volumes:
      - ./pihole/conf/:/etc/pihole/
      - ./pihole/dnsmasq.d/conf/:/etc/dnsmasq.d/
      # run `touch ./var-log/pihole.log` first unless you like errors
      - './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    labels:
        com.centurylinklabs.watchtower.enable: "true"
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    networks:
      - app-nw

networks:
  app-nw:
    internal: false
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-pihole